# Generated by Django 5.1.1 on 2025-02-26 16:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Дата лога"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневный лог",
                "verbose_name_plural": "Ежедневные логи",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название симптома", max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Симптом",
                "verbose_name_plural": "Симптомы",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="SymptomCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название категории симптомов",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание категории", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория симптома",
                "verbose_name_plural": "Категории симптомов",
            },
        ),
    ]
