# Generated by Django 5.1.1 on 2024-10-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="symptom",
            unique_together={("name", "category")},
        ),
    ]
