# Generated by Django 5.1.1 on 2025-02-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("health", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="pet",
            field=models.ForeignKey(
                help_text="Питомец",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="pets.pet",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="symptoms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Симптомы",
                related_name="daily_logs",
                to="health.symptom",
            ),
        ),
        migrations.AddField(
            model_name="symptom",
            name="category",
            field=models.ForeignKey(
                help_text="Категория симптома",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="symptoms",
                to="health.symptomcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("pet", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="symptom",
            unique_together={("name", "category")},
        ),
    ]
