# Generated by Django 5.1.1 on 2024-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="reminder_type",
            field=models.CharField(
                blank=True,
                help_text="Type of reminder",
                max_length=255,
                null=True,
            ),
        ),
    ]
