# Generated by Django 5.1.1 on 2025-02-26 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0002_initial"),
        ("reminders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="owner",
            field=models.ForeignKey(
                help_text="Owner of the reminder",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="pets",
            field=models.ManyToManyField(
                help_text="Related pets for the reminder",
                related_name="reminders",
                to="pets.pet",
            ),
        ),
        migrations.AddField(
            model_name="remindertype",
            name="category",
            field=models.ForeignKey(
                help_text="Category to which this type belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types",
                to="reminders.remindercategory",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="reminder_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of reminder",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reminders",
                to="reminders.remindertype",
            ),
        ),
    ]
