# Generated by Django 5.1.1 on 2024-10-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0005_alter_pet_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Walk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="The start time of the walk"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The end time of the walk",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the walk in minutes",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The owner of the walk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        help_text="The pet being walked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walks",
                        to="pets.pet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalkStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The date of the aggregated walks"),
                ),
                (
                    "total_duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total duration of walks in minutes",
                    ),
                ),
                (
                    "total_walks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of walks",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walk_stats",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "unique_together": {("pet", "date")},
            },
        ),
    ]
