# Generated by Django 5.1.1 on 2024-09-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование языка",
                        max_length=255,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код языка",
                        max_length=10,
                        verbose_name="Код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование страны",
                        max_length=255,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код страны",
                        max_length=10,
                        verbose_name="Код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "indexes": [
                    models.Index(fields=["name"], name="locations_c_name_b70dbe_idx"),
                    models.Index(fields=["code"], name="locations_c_code_9c92f4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование города",
                        max_length=255,
                        verbose_name="Город",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Страна",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="locations.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "indexes": [
                    models.Index(fields=["name"], name="locations_c_name_5719ba_idx"),
                ],
            },
        ),
    ]
