# Generated by Django 5.1.1 on 2024-09-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL изображения",
                        max_length=2048,
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Тип изображения",
                        max_length=255,
                        null=True,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание изображения",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мультимедиа",
                "verbose_name_plural": "Мультимедиа",
                "indexes": [
                    models.Index(fields=["type"], name="media_multi_type_3ec45a_idx")
                ],
            },
        ),
    ]
