# Generated by Django 5.1.1 on 2025-02-26 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the breed", max_length=100, unique=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        help_text="The size of the breed",
                        max_length=20,
                    ),
                ),
                (
                    "exercise_needs",
                    models.IntegerField(help_text="Exercise needs in minutes per day"),
                ),
                (
                    "grooming_requirements",
                    models.IntegerField(help_text="Grooming frequency in days"),
                ),
                ("coat_length", models.CharField(max_length=50)),
                ("sheds", models.BooleanField(default=True)),
                (
                    "lifespan",
                    models.IntegerField(help_text="The lifespan of the breed in years"),
                ),
                (
                    "min_weight",
                    models.FloatField(
                        help_text="The minimum weight of the breed in Lbs"
                    ),
                ),
                (
                    "max_weight",
                    models.FloatField(
                        help_text="The maximum weight of the breed in Lbs"
                    ),
                ),
                (
                    "min_height",
                    models.FloatField(
                        help_text="The minimum height of the breed in inches"
                    ),
                ),
                (
                    "max_height",
                    models.FloatField(
                        help_text="The maximum height of the breed in inches"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Temperament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Friendly", "Friendly"),
                            ("Playful", "Playful"),
                            ("Loyal", "Loyal"),
                            ("Protective", "Protective"),
                            ("Energetic", "Energetic"),
                            ("Calm", "Calm"),
                            ("Independent", "Independent"),
                            ("Intelligent", "Intelligent"),
                            ("Stubborn", "Stubborn"),
                            ("Affectionate", "Affectionate"),
                            ("Anxious", "Anxious"),
                            ("Aggressive", "Aggressive"),
                            ("Gentle", "Gentle"),
                            ("Adventurous", "Adventurous"),
                            ("Shy", "Shy"),
                            ("Sociable", "Sociable"),
                            ("Well-Balanced", "Well-Balanced"),
                        ],
                        help_text="The name of the temperament",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Dog", "Dog"),
                            ("Cat", "Cat"),
                            ("Bird", "Bird"),
                            ("Reptile", "Reptile"),
                            ("Other", "Other"),
                        ],
                        default="Dog",
                        help_text="The type of the pet",
                        max_length=20,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="The avatar of the pet",
                        null=True,
                        upload_to="pets",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the pet",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="The birth date of the pet", null=True
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "is_neutered",
                    models.BooleanField(
                        blank=True, help_text="Whether the pet is neutered", null=True
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="The weight of the pet", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the pet was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time the pet was last updated",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        help_text="The breed of the pet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pets.breed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
    ]
