# Generated by Django 5.1.1 on 2025-02-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                help_text="The owner of the pet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
