# Generated by Django 5.1.1 on 2024-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="temperament",
            field=models.ManyToManyField(
                blank=True,
                help_text="The temperament of the pet",
                to="pets.temperament",
            ),
        ),
    ]
