# Generated by Django 5.1.1 on 2024-09-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_alter_pet_temperament"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="gender",
            new_name="sex",
        ),
    ]
