# Generated by Django 5.1.1 on 2024-10-03 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_remove_pet_birth_day_remove_pet_birth_month_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                help_text="The owner of the pet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
